<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Force full width content layout
// add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_entry_content'); // Add custom loop
add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd');
    $background_mobile = get_field('background_mobile', get_the_ID());
    $enable_banner_cta = get_field('enable_banner_cta');
    $on_page_nav = get_field('in-page_nav');
    ?>
    <section class="<?php echo $on_page_nav ? 'has-on-page-nav ' : ''; echo $enable_banner_cta ? 'banner-with-cta ' : ''; ?>banner banner-single-post <?php echo (empty($hero_url)) ? 'empty' : null ?>">
        <div class="banner__rotate bg-cover white" data-mobile="<?php echo $background_mobile ?>"
             style="background-image: url(<?php echo $hero_url ?>);">

            <?php if (!empty($background_mobile)): ?>
                <style>
                    @media screen and (max-width: 960px) {
                        .banner__rotate {
                            background-image: url(<?php echo $background_mobile ?>) !important;
                        }
                </style>
            <?php endif; ?>

            <div class="banner__content">

                <?php if( $enable_banner_cta ) : ?>
                    <?php
                        if ( function_exists('yoast_breadcrumb') ) {
                        yoast_breadcrumb( '<p id="breadcrumbs">','</p>' );
                        }
                    ?>
                    
                    <h1 class="banner__title"><?php the_title() ?></h1>

                    <?php if( get_field('banner_intro_copy') ) : ?>
                        <p class="intro-copy"><?php the_field('banner_intro_copy'); ?></p>
                    <?php endif; ?>

                    <?php $cta_group = get_field('cta_block');
                    $copy = $cta_group['copy'];
                    $button = $cta_group['button'];
                    if( $copy && $button ) : ?>
                        <div class="cta-wrapper">
                            <p><?php echo $copy; ?></p>
                            <a class="button" href="<?php echo $button['url']; ?>" class="col2"><?php echo $button['title']; ?></a>
                        </div>
                    <?php endif; ?>

                <?php else : ?>
                <h1 class="banner__title"><?php the_title() ?></h1>

                <?php endif; ?>

                <?php if ($item2 = get_field('position')): ?>
                    <h3><?php echo $item2 ?></h3>
                <?php endif; ?>
                <?php if ($link = get_field('contact_link')): ?>
                    <div class="button__container">
                        <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                           target="<?php if ($link['target']) {
                               echo $link['target'];
                           } else {
                               echo '_parent';
                           } ?>"><?php echo $link['title']; ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </section>


    <?php if( have_rows('in-page_nav') ) : ?>
    <div class="in-page-nav">
        <div class="col1">
            <h3>On this page</h3>
        </div>
        <div class="col2">
            <?php while( have_rows('in-page_nav') ) : the_row(); ?>
                <a href="#<?php the_sub_field('anchor_link') ?>"><?php the_sub_field('title'); ?></a>
            <?php endwhile; ?>
        </div>
    </div>
    <?php endif; ?>



<?php }

function custom_entry_content()
{ ?>
    <div id="main_container">
        <div class="default-page-container">

            <div class="grid-container">
                <div class="grid-x grid-margin-x list-decor">

                    <?php if (have_posts()) : ?>
                        <?php while (have_posts()) : the_post(); ?>
                            <div class="cell">
                                <?php add_filter('the_content', 'wpautop'); ?>
                                <?php the_content(); ?>
                            </div>
                        <?php endwhile; ?>
                    <?php endif; ?>
                </div>

            </div>
        </div>
    </div>
<?php }

genesis();
?>
